name: Release all map modules
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Replace assets of an existing version
        type: boolean
        default: false
permissions:
  contents: write
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        module_path:
          - submodules/logos-maps/modules/osm_registry
          - submodules/logos-maps/modules/osm_distribution
    uses: ./.github/workflows/_release-module.yml
    with:
      module_path: ${{ matrix.module_path }}
      force_build: ${{ inputs.force_build }}
    secrets: inherit
